// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace com.kylepeplow.gamestracker.data
{

public enum Format : sbyte
{
 Physical = 0,
 Digital = 1,
};


}
