// automatically generated by the FlatBuffers compiler, do not modify

package com.kylepeplow.gamestracker.data;

public final class Format {
  private Format() { }
  public static final byte Physical = 0;
  public static final byte Digital = 1;

  public static final String[] names = { "Physical", "Digital", };

  public static String name(int e) { return names[e]; }
}

