// automatically generated by the FlatBuffers compiler, do not modify

package com.kylepeplow.gamestracker.transmission;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Platform extends Table {
  public static Platform getRootAsPlatform(ByteBuffer _bb) { return getRootAsPlatform(_bb, new Platform()); }
  public static Platform getRootAsPlatform(ByteBuffer _bb, Platform obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Platform __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long id() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }
  public boolean mutateId(long id) { int o = __offset(4); if (o != 0) { bb.putInt(o + bb_pos, (int)id); return true; } else { return false; } }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public byte format() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean mutateFormat(byte format) { int o = __offset(8); if (o != 0) { bb.put(o + bb_pos, format); return true; } else { return false; } }

  public static int createPlatform(FlatBufferBuilder builder,
      long id,
      int nameOffset,
      byte format) {
    builder.startObject(3);
    Platform.addName(builder, nameOffset);
    Platform.addId(builder, id);
    Platform.addFormat(builder, format);
    return Platform.endPlatform(builder);
  }

  public static void startPlatform(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addId(FlatBufferBuilder builder, long id) { builder.addInt(0, (int)id, (int)0L); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addFormat(FlatBufferBuilder builder, byte format) { builder.addByte(2, format, 0); }
  public static int endPlatform(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

